### ISSUE TITLE
YMChatbot-Android Repo is down

### ISSUE THREAD

**Issue by afsabhishek** [yellowmessenger/YMChatbot-Android#91]
![image](https://github.com/yellowmessenger/YMChatbot-Android/assets/1177239/c1d6089d-c44f-4911-9fde-1d3e72b58d41)

**Comment by sankalp211** [comment]
Please add the following code to your Gradle file. It will be helpful.

```
dependencies {
	        implementation 'com.github.yellowmessenger:YMChatbot-Android:v2.9.0'
	}
```

**Comment by afsabhishek** [comment]
Hi Sankalp,

Everything was added. Only issue with YMChatbot is that where ever it is
hosted, it allows only the latest version. For older version there is no
reference.

Regards,
Abhishek Kumar
Mobile: +91 9663082731 | LinkedIn
<https://in.linkedin.com/in/abhishek-kumar-96a2b023>

**Comment by srbbans** [comment]
Hi YM Team,

same issue here...

Could not resolve com.github.yellowmessenger:YMChatbot-Android:2.3.3

Kindly keep support for the older versions.. most of the times we get these issues..

regards-
Sourabh
