### ISSUE TITLE
YM repo is down

### ISSUE THREAD

**Issue by srbbans** [yellowmessenger/YMChatbot-Android#93]
Hi YM Team,

same issue here...

Could not resolve com.github.yellowmessenger:YMChatbot-Android:2.3.3

Kindly keep support for the older versions.. most of the times we get these issues..

regards-
Sourabh

**Comment by sankalp211** [comment]
Hello @srbbans,

All released builds are permanently available; we never remove any previous versions. It appears there's a typo in your Gradle file. To fix this, please update your dependencies block as shown below for version 2.3.3:

```gradle
dependencies {
    implementation 'com.github.yellowmessenger:YMChatbot-Android:v2.3.3'
}
```

This should resolve the issue. Let me know if you need further assistance!

**Comment by srbbans** [comment]
Hi Sankalp,

We are using this in gradle file.

implementation 'com.github.yellowmessenger:YMChatbot-Android:2.3.3'

doesn't seems a typo here... 

Kindly find the logs below..

> Could not resolve all files for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not resolve com.github.yellowmessenger:YMChatbot-Android:v2.3.3.
     Required by:
         project :app
      > Could not resolve com.github.yellowmessenger:YMChatbot-Android:v2.3.3.
         > Could not get resource 'https://maven.cashfree.com/release/com/github/yellowmessenger/YMChatbot-Android/v2.3.3/YMChatbot-Android-v2.3.3.pom'.
            > Could not GET 'https://maven.cashfree.com/release/com/github/yellowmessenger/YMChatbot-Android/v2.3.3/YMChatbot-Android-v2.3.3.pom'. Received status code 403 from server: Forbidden
